x-flowrulz-env: &flowrulz-env
  FLOWRULZ_PERSIST_PATH: /data/rules.json
  FLOWRULZ_SEEDS: node-1:9090,node-2:9091,node-3:9092

services:
  flowrulz-node-1:
    build: .
    hostname: node-1
    environment:
      <<: *flowrulz-env
      FLOWRULZ_NODE_ID: node-1
      FLOWRULZ_HTTP_ADDR: ":8080"
      FLOWRULZ_GRPC_ADDR: ":9090"
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - node1-data:/data

  flowrulz-node-2:
    build: .
    hostname: node-2
    depends_on:
      flowrulz-node-1:
        condition: service_started
    environment:
      <<: *flowrulz-env
      FLOWRULZ_NODE_ID: node-2
      FLOWRULZ_HTTP_ADDR: ":8081"
      FLOWRULZ_GRPC_ADDR: ":9091"
    ports:
      - "8081:8081"
      - "9091:9091"
    volumes:
      - node2-data:/data

  flowrulz-node-3:
    build: .
    hostname: node-3
    depends_on:
      flowrulz-node-1:
        condition: service_started
    environment:
      <<: *flowrulz-env
      FLOWRULZ_NODE_ID: node-3
      FLOWRULZ_HTTP_ADDR: ":8082"
      FLOWRULZ_GRPC_ADDR: ":9092"
    ports:
      - "8082:8082"
      - "9092:9092"
    volumes:
      - node3-data:/data

volumes:
  node1-data:
  node2-data:
  node3-data:
