apiVersion: v1
kind: Service
metadata:
  name: flowrulz
  namespace: {{ include "flowrulz.namespace" . }}
  labels:
    app: flowrulz
spec:
  ports:
    - port: {{ .Values.flowrulz.ports.http }}
      targetPort: {{ .Values.flowrulz.ports.http }}
      name: http
    - port: {{ .Values.flowrulz.ports.grpc }}
      targetPort: {{ .Values.flowrulz.ports.grpc }}
      name: grpc
  clusterIP: None
  selector:
    app: flowrulz
