{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flowrulz
  namespace: {{ include "flowrulz.namespace" . }}
  annotations: {{ toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.flowrulz.host }}
      http:
        paths:
          {{- range .Values.ingress.flowrulz.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: flowrulz
                port:
                  number: {{ $.Values.flowrulz.ports.http }}
          {{- end }}
    {{- if .Values.sim.enabled }}
    - host: {{ .Values.ingress.sim.host }}
      http:
        paths:
          {{- range .Values.ingress.sim.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: sim
                port:
                  number: {{ $.Values.sim.port }}
          {{- end }}
    {{- end }}
{{- end }}
