apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flowrulz
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - pvc.yaml
  - flowrulz.yaml
  - simulator.yaml
  - ingress.yaml
